// vue-app/src/components/HomePage.vue
<template>
  <div>
    <img
      src="https://www.thespruce.com/thmb/Xb4aZlD4-FAvreSOKpAYeau2fj8=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/king-eider-drake-5b2a91a33418c60036872a30.jpg"
    />
    <div class="navigation">
      <router-link to="/page1">Page 1</router-link>
      <router-link to="/page2">Page 2</router-link>
    </div>
  </div>
</template>

<script>
export default {
  name: 'HomePage',
  props: {}
}
</script>

// react-app/src/components/HomePage.js
import React from 'react'
import { Link } from 'react-router-dom'

const HomePage = () => (
  <div>
    <img
      src="https://static.scientificamerican.com/sciam/cache/file/32665E6F-8D90-4567-9769D59E11DB7F26_source.jpg?w=590&h=800&7E4B4CAD-CAE1-4726-93D6A160C2B068B2"
      alt=""
    />
    <div className="navigation">
      <Link to="/page1">Page 1</Link>
      <Link to="/page2">Page 2</Link>
    </div>
  </div>
)

export default HomePage
