// vue-app/src/components/Page1.vue
<template>
  <div>
    <img
      src="https://static.independent.co.uk/s3fs-public/thumbnails/image/2018/12/06/15/Mandarin-duck.jpg"
      alt
    />
    <div class="navigation">
      <router-link to="/">Retour</router-link>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Page1',
  props: {}
}
</script>

// react-app/src/components/Page1.js
import React from 'react'
import { Link } from 'react-router-dom'

const Page1 = () => (
  <div>
    <img
      src="http://www.pethealthnetwork.com/sites/default/files/content/images/5-silent-killers-cats-475212379.jpg"
      alt=""
    />
    <div className="navigation">
      <Link to="/">Retour</Link>
    </div>
  </div>
)

export default Page1
